package org.mypackage.hello;
// Generated 01-Apr-2018 11:05:39 by Hibernate Tools 4.3.1



/**
 * Blog generated by hbm2java
 */
public class Blog  implements java.io.Serializable {


     private int id;
     private String surname;
     private String firstname;

    public Blog() {
    }

	
    public Blog(int id) {
        this.id = id;
    }
    public Blog(int id, String surname, String firstname) {
       this.id = id;
       this.surname = surname;
       this.firstname = firstname;
    }
    public Blog(String surname, String firstname) {
       this.surname = surname;
       this.firstname = firstname;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }




}


